### PR TITLE
#362 reveal withOptions and #365 add withRepresentation

### LINKED ISSUE #362: return RootExpect for assertion verbs
*Affected Version*: 0.9.1
*API* (fluent-en_GB, cc or cc-infix): all
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): all

## How to reproduce the problem  
Consider the following code snippet
```kotlin
expect("this dummy text").withOptions(....)
```
withOptions is not available since the assertion verbs return Expect and not RootExpect

thanks to @matejdro for the report

### LINKED ISSUE #365: change withOptions(textRepresentation=..) to withRepresentation
*Platform* (jvm, js, android): all
*Extension* (none, kotlin 1.3, jdk8): none

## Code related feature
```
expect(listOf(1, 2)).withRepresentation("treated as raw string")
expect(listOf(1, 2)).withRepresentation { "subject based text: $it" }
```

For more information see, https://github.com/robstoll/atrium-roadmap/issues/72

### PR DESCRIPTION
**Pull request by robstoll**
- fixes #362 
- resolves #365 

----
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

### CODE REVIEW

File: apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt [hunk 1]
```diff
@@ -15,19 +16,37 @@ import ch.tutteli.atrium.reporting.reporter
...
- * (which defaults to the subject itself).
+ * Wraps the given [textRepresentation] into a [RawString] and uses it as representation of the subject
+ * instead of the so far defined representation (which defaults to the subject as such).
+ *
+ * In case [Expect.maybeSubject] is not defined i.e. [None], then the previous representation is used.
  */
 @ExperimentalWithOptions
-fun <T> RootExpect<T>.withOptions(textRepresentation: String): Expect<T> =
-    withOptions(ExpectOptions(representation = RawString.create(textRepresentation)))
+fun <T> RootExpect<T>.withRepresentation(textRepresentation: String): Expect<T> =
```
Comment (jGleitz) [inline apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt]: why the upcast? I.e. why does this method not return `RootExpect<T>`?

File: apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt [hunk 2]
```diff
@@ -15,19 +16,37 @@ import ch.tutteli.atrium.reporting.reporter
...
+ *
+ * Notice, if you want to use text (e.g. a [String]) as representation,
+ * then wrap it into a [RawString] via [RawString.create] and pass the [RawString] instead.
+ * If your text does not include the current subject, then we recommend to use the other overload which expects
+ * a `String` and does the wrapping for you.
+ *
+ * In case [Expect.maybeSubject] is not defined i.e. [None], then the previous representation is used.
+ */
+@ExperimentalWithOptions
+fun <T> RootExpect<T>.withRepresentation(representationProvider: (T) -> Any): Expect<T> =
```
Comment (jGleitz) [inline apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt]: why the upcast? I.e. why does this method not return `RootExpect<T>`?

File: apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt [hunk 3]
```diff
@@ -15,19 +16,37 @@ import ch.tutteli.atrium.reporting.reporter
 annotation class ExperimentalWithOptions
 
 /**
- * Uses the given [textRepresentation] as representation of the subject instead of the current representation
- * (which defaults to the subject itself).
+ * Wraps the given [textRepresentation] into a [RawString] and uses it as representation of the subject
+ * instead of the so far defined representation (which defaults to the subject as such).
```
Comment (jGleitz) [inline apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt]:
```suggestion
 * instead of the representation that has been defined so far (which defaults to the subject itself).
```

File: apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt [hunk 4]
```diff
@@ -15,19 +16,37 @@ import ch.tutteli.atrium.reporting.reporter
...
  */
 @ExperimentalWithOptions
-fun <T> RootExpect<T>.withOptions(textRepresentation: String): Expect<T> =
-    withOptions(ExpectOptions(representation = RawString.create(textRepresentation)))
+fun <T> RootExpect<T>.withRepresentation(textRepresentation: String): Expect<T> =
+    withOptions { withRepresentation(textRepresentation) }
+
+/**
+ * Uses the given [representationProvider] to retrieve a representation which can be based on the current
+ * subject where it is used as new representation of the subject
```
Comment (jGleitz) [inline apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt]:
```suggestion
 * subject. The created value is used as the new representation of the subject
```

File: apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt [hunk 5]
```diff
@@ -15,19 +16,37 @@ import ch.tutteli.atrium.reporting.reporter
...
+ * instead of the so far defined representation (which defaults to the subject as such).
```
Comment (jGleitz) [inline apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt]:
```suggestion
 * instead of the representation that has been defined so far (which defaults to the subject itself).
```

File: apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt [hunk 6]
```diff
@@ -37,23 +56,43 @@ fun <T> RootExpect<T>.withOptions(configuration: ExpectBuilder.OptionsChooser.()
...
 /**
- * Uses the given [textRepresentation] as representation of the subject instead of the current representation
- * (which defaults to the subject itself).
+ * Wraps the given [textRepresentation] into a [RawString] and uses it as representation of the subject
+ * instead of the so far defined representation (which defaults to the subject as such).
+ *
+ * In case [Expect.maybeSubject] is not defined i.e. [None], then the previous representation is used.
+ */
+@ExperimentalWithOptions
+fun <T, R> FeatureExpect<T, R>.withRepresentation(textRepresentation: String): Expect<R> =
```
Comment (jGleitz) [inline apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt]: why the upcast? I.e. why does this method not return `FeatureExpect<T, R>`?

File: apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt [hunk 7]
```diff
@@ -37,23 +56,43 @@ fun <T> RootExpect<T>.withOptions(configuration: ExpectBuilder.OptionsChooser.()
...
+ * then wrap it into a [RawString] via [RawString.create] and pass the [RawString] instead.
+ * If your text does not include the current subject, then we recommend to use the other overload which expects
+ * a `String` and does the wrapping for you.
+ *
+ * In case [Expect.maybeSubject] is not defined i.e. [None], then the previous representation is used.
  */
 @ExperimentalWithOptions
-fun <T, R> FeatureExpect<T, R>.withOptions(textRepresentation: String): Expect<R> =
-    withOptions { withTextRepresentation(textRepresentation) }
+fun <T, R> FeatureExpect<T, R>.withRepresentation(representationProvider: (R) -> Any): Expect<R> =
```
Comment (jGleitz) [inline apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt]: why the upcast? I.e. why does this method not return `FeatureExpect<T, R>`?

File: apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt (hunk 1 above)
Comment (robstoll) [reply apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt]: because:
- we don't restrict ourselfs and we can return a different representation later on without binary bc; I am not yet sure if we can return RootExpect once we have an immutable structure
- IMO it does not make sense to do `withOptions(...).withOptions(...)` one can set a property multiple times within the withOptions lambda.

The same reasoning applies to FeatureExpect below

File: apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt (hunk 4 above)
Comment (robstoll) [reply apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/fluent/en_GB/expectExtensions.kt]: I know it is quite a long sentence but I have the feeling the first sentence should cover the main functionality
